### ISSUE TITLE
JEDchecked in Joomla 3.10.12 failed: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by peterhulst** [joomla-extensions/jedchecker#206]
When the JEDchecker is installed in J3.10.12 the installation is okay.

However after _Submit_ and than _Check_, in all steps the following is displayed:

**TypeError: Failed to fetch**

**Comment by dryabov** [comment]
Should be fixed by PR #207.

**Comment by peterhulst** [comment]
It still does not work. The same error message. I have also  cleared the cache because of the changed JS-file.

**Comment by dryabov** [comment]
Hmm, I've just setup a new J!3.10.12 website, installed current JEDChecker snapshot, and it works well there.
Could you check `media/com_jedchecker/js/script.js` file on your website has `jQuery.fn.scrollspy.noConflict();` line near the end of the file?

**Comment by peterhulst** [comment]
Mmmm, strange.
That line is correctly in place. So it must be something in my installation. 
I will later install a clean version of 3.10.12 and check again.

**Comment by dryabov** [comment]
Do you have a stacktrace in browser's console for this error? If yes, could you post it here.

And check PHP's `error_log`, maybe there is an error that results in "Failed to fetch" on the browser side.

**Comment by peterhulst** [comment]
GOOD NEWS!
There is no message in the error_log.

But I have found a solution! 
When in Global Configuration, Debug System:  No --> **Yes** 
the JED Checker works now in J3.
Thank you for your help.

**Comment by dryabov** [comment]
Let's don't sweep it under the carpet. Unfortunately :-) on my site JEDChecker work with both Debug enabled and disabled, but I'd like to found a way to reproduce the issue or get more details to fix it.

The `TypeError: Failed to fetch` error means that a request to `index.php?option=com_jedchecker&task=police.check&format=raw&rule=...` failed for unknown reason. Maybe Network tab in browser's developer tools contains more details (e.g. status code is not 200).

**Comment by peterhulst** [comment]
See below the content of the Network tab (**with Debug: No**). May be it helps you.
If you want to know more, let me know.

![image](https://github.com/joomla-extensions/jedchecker/assets/8728563/8a98606b-4f8e-4c40-8388-7f73c9af369b)

**Comment by dryabov** [comment]
@peterhulst It's screenshot of Console tab. Could open the Network tab, found related request there (e.g. the last one with `task=police.check` in URL), click on it with right mouse button, select `Copy`>`Copy response headers`, and post them there?

But usually `net::ERR_CONTENT_DECODING_FAILED` means either a double-gzipping issue or an incorrect content length issue. Do you have a 3rdparty optimization extension installed on website?

**Comment by peterhulst** [comment]
_Here are the Reponse headers:_

HTTP/1.1 200 OK
Date: Fri, 28 Jul 2023 11:07:16 GMT
Server: Apache/2.4.54 (Win64) OpenSSL/1.1.1q mod_fcgid/2.3.10-dev
X-Powered-By: PHP/8.0.28
Content-Encoding: gzip
Vary: Accept-Encoding
Expires: Wed, 17 Aug 2005 00:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Content-Type-Options: nosniff
Last-Modified: Fri, 28 Jul 2023 11:07:17 GMT
Keep-Alive: timeout=5, max=97
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: text/html; charset=utf-8

![image](https://github.com/joomla-extensions/jedchecker/assets/8728563/0bb22246-f695-48d5-8500-3913bc2f441d)

**Comment by dryabov** [comment]
And if you switch from Headers to Response tab there, what response content is displayed?

**Comment by peterhulst** [comment]
![image](https://github.com/joomla-extensions/jedchecker/assets/8728563/9762fe3c-cbfd-4389-8fd8-ae1577249052)

**Comment by dryabov** [comment]
What is your OS? Do you have `curl` cli tool installed? If yes, could you try to copy request (`Copy`>`Copy as cURL (bash)`) and run it in cli (bash/sh/cmd/whatever) with and without `--compressed` argument?

**Comment by peterhulst** [comment]
**I have performed what you did in an other setup with curl.**

curl 'https://www.loopgroepbedum.nl/administrator/index.php?option=com_jedchecker&task=police.check&format=raw&rule=xmlinfo' \
  -H 'authority: www.loopgroepbedum.nl' \
  -H 'accept: */*' \
  -H 'accept-language: nl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7' \
  -H 'authorization: Basic bGdiZWR1bTpMb29wZ3JvZXBiZWR1bTEyISE=' \
  -H 'cookie: editorswitchercurrent=jce; editorswitchercurrent=jce; __atssc=facebook%3B7; __atuvc=26%7C18%2C70%7C19%2C236%7C20%2C50%7C21%2C8%7C22; _ga=GA1.1.162843822.1669240905; 583540281f79f3a110dfec49c113275d=oovgii79n86a63qsdvjl4cg6cs; _ga_6Z16LTQ0JX=GS1.1.1690541623.54.1.1690541623.0.0.0; a09f60020bc1fdce5c88780e0075036f=nj8ell83i09jshuoshgujjc1ge' \
  -H 'referer: https://www.loopgroepbedum.nl/administrator/index.php?option=com_jedchecker&view=uploads' \
  -H 'sec-ch-ua: "Not/A)Brand";v="99", "Microsoft Edge";v="115", "Chromium";v="115"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183' \


**gives:**

Task "curl 'https://www.loopgroepbedum.nl/administrator/index.php?option=com_jedchecker&task=police.check&format=raw&rule=xmlinfo' \ -H 'authority: www.loopgroepbedum.nl' \ -H 'accept: */*' \ -H 'accept-language: nl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7' \ -H 'authorization: Basic bGdiZWR1bTpMb29wZ3JvZXBiZWR1bTEyISE=' \ -H 'cookie: editorswitchercurrent=jce; editorswitchercurrent=jce; __atssc=facebook%3B7; __atuvc=26%7C18%2C70%7C19%2C236%7C20%2C50%7C21%2C8%7C22; _ga=GA1.1.162843822.1669240905; 583540281f79f3a110dfec49c113275d=oovgii79n86a63qsdvjl4cg6cs; _ga_6Z16LTQ0JX=GS1.1.1690541623.54.1.169054

**Comment by dryabov** [comment]
Seems I've found where the issue may come from (thanks to your comment with real server name; I removed that comment as soon as I saw it to don't disclose data): the server sends original uncompressed data followed by compressed empty string. Could you remove line 62 `ob_flush();` from `administrator/components/com_jedchecker/controllers/police.raw.php` file and check work of the JEDChecker again? It should allow Joomla to properly compress response data.

**Comment by peterhulst** [comment]
GOOD NEWS! It works now
I did the modification on line 62 --> 82.
And now all checks run properly.
Glad I can help you.
Regards,
Peter

**Comment by dryabov** [comment]
Thank you very-very much!
